// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTGVRncFu707sWnks1jYrD9G9EH9Kdy0k',
    appId: '1:792704153211:web:76f956e1458c73029114de',
    messagingSenderId: '792704153211',
    projectId: 'airon-chef-c51ad',
    authDomain: 'airon-chef-c51ad.firebaseapp.com',
    databaseURL: 'https://airon-chef-c51ad-default-rtdb.firebaseio.com',
    storageBucket: 'airon-chef-c51ad.firebasestorage.app',
    measurementId: 'G-HZFP80EBX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtpbk8SQVUalYLn6Ji4f59EaY4Hry-jHA',
    appId: '1:792704153211:android:24b2072392bd6e599114de',
    messagingSenderId: '792704153211',
    projectId: 'airon-chef-c51ad',
    databaseURL: 'https://airon-chef-c51ad-default-rtdb.firebaseio.com',
    storageBucket: 'airon-chef-c51ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM01DOw4o8RNoIpXGv9xjsFm7TFVnzH0o',
    appId: '1:792704153211:ios:343b918fe0c853b49114de',
    messagingSenderId: '792704153211',
    projectId: 'airon-chef-c51ad',
    databaseURL: 'https://airon-chef-c51ad-default-rtdb.firebaseio.com',
    storageBucket: 'airon-chef-c51ad.firebasestorage.app',
    iosClientId: '792704153211-0of54160jiusnqb6ikvh2j0820njs6sk.apps.googleusercontent.com',
    iosBundleId: 'com.example.aironChef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM01DOw4o8RNoIpXGv9xjsFm7TFVnzH0o',
    appId: '1:792704153211:ios:343b918fe0c853b49114de',
    messagingSenderId: '792704153211',
    projectId: 'airon-chef-c51ad',
    databaseURL: 'https://airon-chef-c51ad-default-rtdb.firebaseio.com',
    storageBucket: 'airon-chef-c51ad.firebasestorage.app',
    iosClientId: '792704153211-0of54160jiusnqb6ikvh2j0820njs6sk.apps.googleusercontent.com',
    iosBundleId: 'com.example.aironChef',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTGVRncFu707sWnks1jYrD9G9EH9Kdy0k',
    appId: '1:792704153211:web:d12fc2516d2963e89114de',
    messagingSenderId: '792704153211',
    projectId: 'airon-chef-c51ad',
    authDomain: 'airon-chef-c51ad.firebaseapp.com',
    databaseURL: 'https://airon-chef-c51ad-default-rtdb.firebaseio.com',
    storageBucket: 'airon-chef-c51ad.firebasestorage.app',
    measurementId: 'G-54S2CJ5076',
  );
}
